import type { ClauseDelta } from "@/lib/types";

export const CLAUSE_DELTAS: ClauseDelta[] = [
  // ── cd-001: GL Pollution Exclusion ──
  {
    id: "cd-001",
    title: "Pollution Exclusion — Hostile Fire Exception",
    coverageType: "General Liability",
    naicsCode: "238220",
    naicsDescription: "Plumbing, Heating, and Air-Conditioning Contractors",
    direction: "tighter",
    mechanism: "exclusion",
    severity: "high",
    confidence: 0.94,
    abstained: false,
    markelSpan: {
      fullText:
        "This insurance does not apply to bodily injury or property damage arising out of the actual, alleged or threatened discharge, dispersal, seepage, migration, release or escape of pollutants. This exclusion does not apply to bodily injury or property damage arising out of heat, smoke or fumes from a hostile fire.",
      highlightStart: 145,
      highlightEnd: 275,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 14,
        clauseId: "CG-00-01-Section-I-2f",
        extractionConfidence: 0.96,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T10:30:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "This insurance does not apply to bodily injury or property damage which would not have occurred in whole or in part but for the actual, alleged or threatened discharge, dispersal, seepage, migration, release or escape of pollutants at any time. No exception is provided for hostile fire events under this exclusion.",
      highlightStart: 215,
      highlightEnd: 310,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 16,
        clauseId: "KGL-EX-2f",
        extractionConfidence: 0.95,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T10:32:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale removes the hostile fire exception from its pollution exclusion, meaning that pollution-related claims from fires are excluded even if the fire was not set intentionally. Markel retains this standard exception.",
    reasoningSteps: [
      "Identified pollution exclusion in both GL forms (CG 00 01 equivalent).",
      "Markel form retains the ISO-standard hostile fire exception at Section I, 2(f)(1)(d).",
      "Kinsale form explicitly states no exception is provided for hostile fire events.",
      "This creates a gap where HVAC contractors with refrigerant release during a fire would be excluded under Kinsale but potentially covered under Markel.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 14,
      clauseId: "CG-00-01-Section-I-2f",
      extractionConfidence: 0.96,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T10:30:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 16,
      clauseId: "KGL-EX-2f",
      extractionConfidence: 0.95,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T10:32:00Z",
    },
  },

  // ── cd-002: GL Products-Completed Operations Aggregate ──
  {
    id: "cd-002",
    title: "Products-Completed Operations Aggregate Limit",
    coverageType: "General Liability",
    naicsCode: "238220",
    naicsDescription: "Plumbing, Heating, and Air-Conditioning Contractors",
    direction: "tighter",
    mechanism: "sublimit",
    severity: "medium",
    confidence: 0.91,
    abstained: false,
    markelSpan: {
      fullText:
        "The Products-Completed Operations Aggregate Limit is the most we will pay under Coverage A for damages because of bodily injury and property damage included in the products-completed operations hazard. This aggregate limit shall be equal to the General Aggregate Limit shown in the Declarations.",
      highlightStart: 0,
      highlightEnd: 155,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 8,
        clauseId: "CG-00-01-Section-III-4",
        extractionConfidence: 0.94,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T10:34:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "The Products-Completed Operations Aggregate Limit is the most we will pay for damages because of bodily injury and property damage included in the products-completed operations hazard. This aggregate limit shall not exceed fifty percent (50%) of the General Aggregate Limit shown in the Declarations.",
      highlightStart: 168,
      highlightEnd: 300,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 9,
        clauseId: "KGL-LIM-4",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T10:36:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale caps the Products-Completed Operations aggregate at 50% of the General Aggregate, while Markel sets it equal to the full General Aggregate. This significantly reduces available limits for completed operations claims under Kinsale.",
    reasoningSteps: [
      "Compared aggregate limit language in both forms' Limits of Insurance section.",
      "Markel sets Products-Completed Operations aggregate equal to the General Aggregate.",
      "Kinsale restricts it to 50% of the General Aggregate.",
      "For a $2M General Aggregate, Kinsale provides only $1M for Products-Completed Ops versus Markel's $2M.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 8,
      clauseId: "CG-00-01-Section-III-4",
      extractionConfidence: 0.94,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T10:34:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 9,
      clauseId: "KGL-LIM-4",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T10:36:00Z",
    },
  },

  // ── cd-003: GL Contractual Liability Definition ──
  {
    id: "cd-003",
    title: "Contractual Liability — Insured Contract Definition",
    coverageType: "General Liability",
    naicsCode: "236220",
    naicsDescription: "Commercial and Institutional Building Construction",
    direction: "tighter",
    mechanism: "definition_narrowing",
    severity: "high",
    confidence: 0.92,
    abstained: false,
    markelSpan: {
      fullText:
        "Insured contract means that part of any other contract or agreement pertaining to your business under which you assume the tort liability of another party to pay for bodily injury or property damage to a third person or organization. Tort liability means a liability that would be imposed by law in the absence of any contract or agreement.",
      highlightStart: 0,
      highlightEnd: 192,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 22,
        clauseId: "CG-00-01-Section-V-9f",
        extractionConfidence: 0.95,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T10:38:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "Insured contract means only a written contract or agreement executed prior to the bodily injury or property damage for which you assume the tort liability of another party. Oral agreements, implied contracts, and any contract executed after the date of loss are specifically excluded from this definition.",
      highlightStart: 92,
      highlightEnd: 302,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 24,
        clauseId: "KGL-DEF-9f",
        extractionConfidence: 0.94,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T10:40:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale narrows the definition of insured contract to require written agreements executed before the loss date and explicitly excludes oral agreements. Markel uses a broader definition that does not impose these restrictions.",
    reasoningSteps: [
      "Extracted 'insured contract' definitions from both forms' Definitions sections.",
      "Markel uses standard ISO language allowing any contract pertaining to the business.",
      "Kinsale adds three restrictions: must be written, must pre-date the loss, and oral/implied agreements are excluded.",
      "Construction contractors frequently rely on oral subcontractor agreements that would not qualify under Kinsale's narrower definition.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 22,
      clauseId: "CG-00-01-Section-V-9f",
      extractionConfidence: 0.95,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T10:38:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 24,
      clauseId: "KGL-DEF-9f",
      extractionConfidence: 0.94,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T10:40:00Z",
    },
  },

  // ── cd-004: PL Claims-Made Retroactive Date ──
  {
    id: "cd-004",
    title: "Claims-Made Retroactive Date Restriction",
    coverageType: "Professional Liability",
    naicsCode: "541511",
    naicsDescription: "Custom Computer Programming Services",
    direction: "tighter",
    mechanism: "condition",
    severity: "high",
    confidence: 0.93,
    abstained: false,
    markelSpan: {
      fullText:
        "This policy applies to claims first made against the insured during the policy period, provided the wrongful act giving rise to the claim occurred on or after the retroactive date shown in the Declarations. If no retroactive date is shown, coverage applies to wrongful acts occurring at any time prior to the end of the policy period.",
      highlightStart: 192,
      highlightEnd: 332,
      provenance: {
        documentId: "doc-markel-pl-01",
        documentName: "Markel PL Policy Form MPL-2024-05",
        pageNumber: 5,
        clauseId: "MPL-IG-1a",
        extractionConfidence: 0.96,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:00:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "Coverage under this policy applies only to claims first made against the insured during the policy period for wrongful acts that occurred on or after the retroactive date shown in the Declarations. A retroactive date is mandatory and must be specified for coverage to attach. No coverage is provided for wrongful acts occurring prior to the stated retroactive date regardless of when the claim is made.",
      highlightStart: 145,
      highlightEnd: 310,
      provenance: {
        documentId: "doc-kinsale-pl-01",
        documentName: "Kinsale PL Policy Form KPL-2024-02",
        pageNumber: 6,
        clauseId: "KPL-IG-1a",
        extractionConfidence: 0.95,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:02:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale requires a mandatory retroactive date, while Markel allows full prior acts coverage when no retroactive date is specified. Software firms with long development cycles face significant gaps under Kinsale's approach.",
    reasoningSteps: [
      "Compared claims-made trigger provisions in both professional liability forms.",
      "Markel provides full prior acts coverage when no retroactive date is declared.",
      "Kinsale mandates a retroactive date and provides no fallback for prior acts.",
      "For software firms, defects discovered years after deployment would be excluded if the retro date postdates the original coding.",
      "This is a high-severity gap for long-tail professional liability exposures.",
    ],
    markelProvenance: {
      documentId: "doc-markel-pl-01",
      documentName: "Markel PL Policy Form MPL-2024-05",
      pageNumber: 5,
      clauseId: "MPL-IG-1a",
      extractionConfidence: 0.96,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:00:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-pl-01",
      documentName: "Kinsale PL Policy Form KPL-2024-02",
      pageNumber: 6,
      clauseId: "KPL-IG-1a",
      extractionConfidence: 0.95,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:02:00Z",
    },
  },

  // ── cd-005: Cyber Network Security Trigger ──
  {
    id: "cd-005",
    title: "Network Security Liability — Trigger Definition",
    coverageType: "Cyber Liability",
    naicsCode: "511210",
    naicsDescription: "Software Publishers",
    direction: "tighter",
    mechanism: "trigger",
    severity: "high",
    confidence: 0.90,
    abstained: false,
    markelSpan: {
      fullText:
        "Network Security Liability means liability arising from failure of computer security to prevent unauthorized access to, unauthorized use of, or a denial of service attack against a computer system. This includes liability arising from the inability of an authorized third party to gain access to your computer system as a result of such failure.",
      highlightStart: 0,
      highlightEnd: 176,
      provenance: {
        documentId: "doc-markel-cy-01",
        documentName: "Markel Cyber Policy Form MCY-2024-09",
        pageNumber: 12,
        clauseId: "MCY-IG-3b",
        extractionConfidence: 0.92,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:10:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "Network Security Liability applies only to liability arising from the failure of computer security to prevent unauthorized access to or unauthorized use of a computer system that is owned, operated, or controlled by the insured. Third-party hosted systems, cloud infrastructure, and managed service provider environments are excluded from this coverage unless specifically endorsed.",
      highlightStart: 147,
      highlightEnd: 383,
      provenance: {
        documentId: "doc-kinsale-cy-01",
        documentName: "Kinsale Cyber Policy Form KCY-2024-01",
        pageNumber: 14,
        clauseId: "KCY-IG-3b",
        extractionConfidence: 0.91,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:12:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale restricts network security coverage to systems owned or controlled by the insured, excluding cloud and third-party hosted environments. Markel's broader language does not impose this ownership requirement, covering failures in any computer system.",
    reasoningSteps: [
      "Extracted network security liability definitions from both cyber forms.",
      "Markel covers failure of computer security broadly without ownership restrictions.",
      "Kinsale requires the system be 'owned, operated, or controlled by the insured.'",
      "Cloud-native software publishers relying on AWS/Azure would have significant gaps under Kinsale.",
      "Denial of service coverage is also absent from Kinsale's language.",
    ],
    markelProvenance: {
      documentId: "doc-markel-cy-01",
      documentName: "Markel Cyber Policy Form MCY-2024-09",
      pageNumber: 12,
      clauseId: "MCY-IG-3b",
      extractionConfidence: 0.92,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:10:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-cy-01",
      documentName: "Kinsale Cyber Policy Form KCY-2024-01",
      pageNumber: 14,
      clauseId: "KCY-IG-3b",
      extractionConfidence: 0.91,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:12:00Z",
    },
  },

  // ── cd-006: EPLI Third-Party Coverage ──
  {
    id: "cd-006",
    title: "Employment Practices — Third-Party Discrimination",
    coverageType: "EPLI",
    naicsCode: "722511",
    naicsDescription: "Full-Service Restaurants",
    direction: "broader",
    mechanism: "exclusion",
    severity: "medium",
    confidence: 0.88,
    abstained: false,
    markelSpan: {
      fullText:
        "This policy provides coverage for claims alleging wrongful employment practices against employees or applicants for employment only. Third-party claims alleging discrimination, harassment, or other wrongful acts by employees against customers, vendors, or other non-employees are excluded from coverage under this form.",
      highlightStart: 99,
      highlightEnd: 310,
      provenance: {
        documentId: "doc-markel-ep-01",
        documentName: "Markel EPLI Policy Form MEP-2024-06",
        pageNumber: 8,
        clauseId: "MEP-IG-2c",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:20:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "This policy provides coverage for claims alleging wrongful employment practices against employees, applicants for employment, and third parties. Third-party coverage extends to claims by customers, clients, or vendors alleging discrimination or harassment by an employee of the insured in the course of their employment duties.",
      highlightStart: 97,
      highlightEnd: 316,
      provenance: {
        documentId: "doc-kinsale-ep-01",
        documentName: "Kinsale EPLI Policy Form KEP-2024-04",
        pageNumber: 9,
        clauseId: "KEP-IG-2c",
        extractionConfidence: 0.92,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:22:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale provides broader EPLI coverage by including third-party discrimination claims from customers and vendors. Markel's form limits coverage to employee and applicant claims only, excluding third-party harassment lawsuits common in the restaurant industry.",
    reasoningSteps: [
      "Compared insuring agreement scope in both EPLI forms.",
      "Markel explicitly limits coverage to employees and applicants.",
      "Kinsale extends coverage to include third-party claims by customers, clients, and vendors.",
      "For full-service restaurants, customer-facing harassment claims are a significant exposure that Kinsale covers but Markel does not.",
    ],
    markelProvenance: {
      documentId: "doc-markel-ep-01",
      documentName: "Markel EPLI Policy Form MEP-2024-06",
      pageNumber: 8,
      clauseId: "MEP-IG-2c",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:20:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-ep-01",
      documentName: "Kinsale EPLI Policy Form KEP-2024-04",
      pageNumber: 9,
      clauseId: "KEP-IG-2c",
      extractionConfidence: 0.92,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:22:00Z",
    },
  },

  // ── cd-007: Umbrella Following Form Condition ──
  {
    id: "cd-007",
    title: "Umbrella — Following Form vs. Stand-Alone Coverage",
    coverageType: "Umbrella",
    naicsCode: "236220",
    naicsDescription: "Commercial and Institutional Building Construction",
    direction: "tighter",
    mechanism: "condition",
    severity: "medium",
    confidence: 0.87,
    abstained: false,
    markelSpan: {
      fullText:
        "This umbrella policy shall follow form with the underlying insurance scheduled herein except as otherwise provided. Coverage shall apply to those occurrences, offenses, wrongful acts, or claims covered by the underlying insurance, subject to the terms, conditions, and exclusions of this policy. Drop-down coverage is provided when underlying limits are exhausted by payment of covered claims.",
      highlightStart: 0,
      highlightEnd: 200,
      provenance: {
        documentId: "doc-markel-um-01",
        documentName: "Markel Umbrella Policy Form MUM-2024-08",
        pageNumber: 4,
        clauseId: "MUM-IG-1",
        extractionConfidence: 0.91,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:30:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "This umbrella policy provides excess coverage only and does not follow form with any underlying insurance. Coverage is limited to those occurrences, offenses, or claims specifically described in this policy. No drop-down coverage is provided when underlying limits are exhausted and the insured must maintain scheduled underlying coverage at all times for this policy to apply.",
      highlightStart: 0,
      highlightEnd: 198,
      provenance: {
        documentId: "doc-kinsale-um-01",
        documentName: "Kinsale Umbrella Policy Form KUM-2024-05",
        pageNumber: 4,
        clauseId: "KUM-IG-1",
        extractionConfidence: 0.90,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:32:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale's umbrella operates as excess-only without following form or drop-down, while Markel's follows form with the scheduled underlying coverage and provides drop-down when underlying limits exhaust. This creates coverage gaps for construction firms needing seamless excess protection.",
    reasoningSteps: [
      "Analyzed the insuring agreements in both umbrella forms.",
      "Markel umbrella follows form with the underlying insurance and provides drop-down coverage.",
      "Kinsale umbrella is excess-only, does not follow form, and has no drop-down provision.",
      "Construction projects with complex underlying coverage layers benefit significantly from Markel's following form approach.",
    ],
    markelProvenance: {
      documentId: "doc-markel-um-01",
      documentName: "Markel Umbrella Policy Form MUM-2024-08",
      pageNumber: 4,
      clauseId: "MUM-IG-1",
      extractionConfidence: 0.91,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:30:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-um-01",
      documentName: "Kinsale Umbrella Policy Form KUM-2024-05",
      pageNumber: 4,
      clauseId: "KUM-IG-1",
      extractionConfidence: 0.90,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:32:00Z",
    },
  },

  // ── cd-008: Property Ordinance or Law Sublimit ──
  {
    id: "cd-008",
    title: "Ordinance or Law — Increased Cost of Construction Sublimit",
    coverageType: "Property",
    naicsCode: "722511",
    naicsDescription: "Full-Service Restaurants",
    direction: "tighter",
    mechanism: "sublimit",
    severity: "medium",
    confidence: 0.89,
    abstained: false,
    markelSpan: {
      fullText:
        "We will pay for the increased cost of construction incurred to comply with the enforcement of any ordinance or law that regulates the construction or repair of damaged buildings. The limit of insurance for this coverage is twenty-five percent (25%) of the building limit of insurance shown in the Declarations.",
      highlightStart: 0,
      highlightEnd: 178,
      provenance: {
        documentId: "doc-markel-pr-01",
        documentName: "Markel Property Policy Form MPR-2024-04",
        pageNumber: 18,
        clauseId: "MPR-AC-5a",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:40:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "We will pay for the increased cost of construction to comply with ordinance or law that regulates the construction or repair of damaged buildings. The most we will pay under this additional coverage is ten percent (10%) of the building limit of insurance shown in the Declarations or $100,000, whichever is less.",
      highlightStart: 148,
      highlightEnd: 306,
      provenance: {
        documentId: "doc-kinsale-pr-01",
        documentName: "Kinsale Property Policy Form KPR-2024-06",
        pageNumber: 20,
        clauseId: "KPR-AC-5a",
        extractionConfidence: 0.92,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:42:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale limits ordinance or law coverage to the lesser of 10% of building value or $100,000, while Markel provides 25% of building value. For restaurants in older buildings subject to code upgrades, this creates a significant coverage gap under Kinsale.",
    reasoningSteps: [
      "Compared Ordinance or Law additional coverage provisions in both property forms.",
      "Markel provides 25% of building limit for increased cost of construction.",
      "Kinsale caps at the lesser of 10% of building limit or $100,000.",
      "For a $1M building, Markel provides $250K versus Kinsale's $100K — a $150K gap.",
    ],
    markelProvenance: {
      documentId: "doc-markel-pr-01",
      documentName: "Markel Property Policy Form MPR-2024-04",
      pageNumber: 18,
      clauseId: "MPR-AC-5a",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:40:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-pr-01",
      documentName: "Kinsale Property Policy Form KPR-2024-06",
      pageNumber: 20,
      clauseId: "KPR-AC-5a",
      extractionConfidence: 0.92,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:42:00Z",
    },
  },

  // ── cd-009: GL Independent Contractors Exclusion ──
  {
    id: "cd-009",
    title: "Independent Contractors — Vicarious Liability Exclusion",
    coverageType: "General Liability",
    naicsCode: "561720",
    naicsDescription: "Janitorial Services",
    direction: "tighter",
    mechanism: "exclusion",
    severity: "high",
    confidence: 0.92,
    abstained: false,
    markelSpan: {
      fullText:
        "Coverage A applies to bodily injury or property damage arising out of operations performed for you by independent contractors, including your general supervision thereof. We will defend and indemnify you for vicarious liability arising from acts of your independent contractors performed within the scope of their engagement.",
      highlightStart: 0,
      highlightEnd: 172,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 10,
        clauseId: "CG-00-01-Section-I-2a-IC",
        extractionConfidence: 0.94,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:50:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "This insurance does not apply to bodily injury or property damage arising out of operations performed for the insured by independent contractors, subcontractors, or temporary staffing personnel. This exclusion applies whether or not the insured supervised, directed, or controlled the work of such independent contractors.",
      highlightStart: 0,
      highlightEnd: 195,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 12,
        clauseId: "KGL-EX-IC",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T11:52:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale excludes all liability arising from independent contractors regardless of supervision, while Markel provides vicarious liability coverage for independent contractor operations. Janitorial companies heavily relying on 1099 workers face total exclusion under Kinsale.",
    reasoningSteps: [
      "Identified independent contractor provisions in both GL forms.",
      "Markel provides affirmative coverage for vicarious liability from independent contractor work.",
      "Kinsale adds a blanket exclusion for all independent contractor operations.",
      "Janitorial services commonly use independent contractors, making this exclusion critical.",
      "No endorsement is available from Kinsale to buy back this coverage.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 10,
      clauseId: "CG-00-01-Section-I-2a-IC",
      extractionConfidence: 0.94,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:50:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 12,
      clauseId: "KGL-EX-IC",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T11:52:00Z",
    },
  },

  // ── cd-010: PL Duty to Defend vs. Reimburse ──
  {
    id: "cd-010",
    title: "Duty to Defend vs. Duty to Reimburse",
    coverageType: "Professional Liability",
    naicsCode: "523930",
    naicsDescription: "Investment Advice",
    direction: "tighter",
    mechanism: "condition",
    severity: "high",
    confidence: 0.95,
    abstained: false,
    markelSpan: {
      fullText:
        "We shall have the right and duty to defend the insured against any claim seeking those damages to which this insurance applies. We will appoint defense counsel and pay all costs of defense in addition to the limit of insurance. Our duty to defend ends when we have used up the applicable limit of insurance in the payment of judgments or settlements.",
      highlightStart: 0,
      highlightEnd: 180,
      provenance: {
        documentId: "doc-markel-pl-01",
        documentName: "Markel PL Policy Form MPL-2024-05",
        pageNumber: 7,
        clauseId: "MPL-DFD-1",
        extractionConfidence: 0.97,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:00:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "We shall not have a duty to defend any claim. The insured shall retain defense counsel of their choosing and we will reimburse reasonable and necessary defense costs, subject to our prior written consent. Defense costs shall be applied against and reduce the limit of insurance available for judgments and settlements.",
      highlightStart: 0,
      highlightEnd: 192,
      provenance: {
        documentId: "doc-kinsale-pl-01",
        documentName: "Kinsale PL Policy Form KPL-2024-02",
        pageNumber: 8,
        clauseId: "KPL-DFD-1",
        extractionConfidence: 0.96,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:02:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale uses duty-to-reimburse with defense costs eroding limits, while Markel provides a duty-to-defend with defense costs in addition to limits. For investment advisors facing regulatory claims, Kinsale's approach can rapidly deplete available limits.",
    reasoningSteps: [
      "Compared defense obligation language in both PL forms.",
      "Markel provides a duty to defend with costs outside the limit of insurance.",
      "Kinsale uses a duty to reimburse with costs inside (eroding) the limit.",
      "For investment advisors, SEC/FINRA defense costs averaging $250K-$500K would consume 25-50% of a $1M limit under Kinsale.",
      "This fundamentally changes the economics of the coverage for financial services firms.",
    ],
    markelProvenance: {
      documentId: "doc-markel-pl-01",
      documentName: "Markel PL Policy Form MPL-2024-05",
      pageNumber: 7,
      clauseId: "MPL-DFD-1",
      extractionConfidence: 0.97,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:00:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-pl-01",
      documentName: "Kinsale PL Policy Form KPL-2024-02",
      pageNumber: 8,
      clauseId: "KPL-DFD-1",
      extractionConfidence: 0.96,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:02:00Z",
    },
  },

  // ── cd-011: Products Liability Recall Exclusion ──
  {
    id: "cd-011",
    title: "Products Liability — Product Recall Expense Exclusion",
    coverageType: "Products Liability",
    naicsCode: "722511",
    naicsDescription: "Full-Service Restaurants",
    direction: "neutral",
    mechanism: "exclusion",
    severity: "low",
    confidence: 0.86,
    abstained: false,
    markelSpan: {
      fullText:
        "This insurance does not apply to any loss, cost, or expense arising out of any recall of products, withdrawal of products from the market, or any inspection, repair, replacement, or loss of use of such products. This exclusion applies regardless of whether the recall is voluntary or mandated by a governmental authority.",
      highlightStart: 0,
      highlightEnd: 192,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 17,
        clauseId: "CG-00-01-Section-I-2k",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:10:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "This insurance does not apply to any loss, cost, or expense arising out of any recall of products, withdrawal of products from the market, or any inspection, repair, replacement, or loss of use of such products, whether such recall is voluntary or mandated by a governmental authority or regulatory body.",
      highlightStart: 0,
      highlightEnd: 195,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 19,
        clauseId: "KGL-EX-2k",
        extractionConfidence: 0.92,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:12:00Z",
      },
    },
    plainLanguageExplanation:
      "Both Markel and Kinsale exclude product recall expenses using substantially identical language. The recall exclusion applies whether the recall is voluntary or government-mandated, with no material difference between the two forms.",
    reasoningSteps: [
      "Extracted product recall exclusion language from both GL forms.",
      "Markel and Kinsale use nearly identical language for this exclusion.",
      "Both exclude voluntary and government-mandated recalls.",
      "No material difference was identified between the two provisions.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 17,
      clauseId: "CG-00-01-Section-I-2k",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:10:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 19,
      clauseId: "KGL-EX-2k",
      extractionConfidence: 0.92,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:12:00Z",
    },
  },

  // ── cd-012: Cyber Ransomware Sublimit ──
  {
    id: "cd-012",
    title: "Cyber Extortion / Ransomware Sublimit",
    coverageType: "Cyber Liability",
    naicsCode: "511210",
    naicsDescription: "Software Publishers",
    direction: "tighter",
    mechanism: "sublimit",
    severity: "high",
    confidence: 0.93,
    abstained: false,
    markelSpan: {
      fullText:
        "We will pay on behalf of the insured the ransom or extortion payment demanded as a direct result of a cyber extortion threat, subject to the full policy aggregate limit. The insured must obtain our prior written consent before making any extortion payment. Coverage includes reasonable and necessary costs to investigate the credibility of any extortion threat.",
      highlightStart: 0,
      highlightEnd: 188,
      provenance: {
        documentId: "doc-markel-cy-01",
        documentName: "Markel Cyber Policy Form MCY-2024-09",
        pageNumber: 16,
        clauseId: "MCY-IG-5",
        extractionConfidence: 0.94,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:20:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "We will pay on behalf of the insured the ransom or extortion payment demanded as a result of a cyber extortion threat, subject to a sublimit of $250,000 or twenty-five percent (25%) of the policy aggregate, whichever is less. This sublimit is part of and not in addition to the policy aggregate limit. Cryptocurrency payments are excluded.",
      highlightStart: 113,
      highlightEnd: 335,
      provenance: {
        documentId: "doc-kinsale-cy-01",
        documentName: "Kinsale Cyber Policy Form KCY-2024-01",
        pageNumber: 18,
        clauseId: "KCY-IG-5",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:22:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale sublimits ransomware payments to $250K or 25% of the aggregate (whichever is less) and excludes cryptocurrency, while Markel covers ransom payments up to the full policy aggregate without cryptocurrency restrictions.",
    reasoningSteps: [
      "Compared cyber extortion provisions in both cyber liability forms.",
      "Markel provides extortion coverage at full policy limits.",
      "Kinsale imposes a $250K/25% sublimit and excludes cryptocurrency payments.",
      "Given that most ransomware demands are now in cryptocurrency, Kinsale's cryptocurrency exclusion effectively eliminates most ransomware coverage.",
      "This is a critical gap for software publishers targeted by ransomware groups.",
    ],
    markelProvenance: {
      documentId: "doc-markel-cy-01",
      documentName: "Markel Cyber Policy Form MCY-2024-09",
      pageNumber: 16,
      clauseId: "MCY-IG-5",
      extractionConfidence: 0.94,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:20:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-cy-01",
      documentName: "Kinsale Cyber Policy Form KCY-2024-01",
      pageNumber: 18,
      clauseId: "KCY-IG-5",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:22:00Z",
    },
  },

  // ── cd-013: GL Assault & Battery Exclusion ──
  {
    id: "cd-013",
    title: "Assault and Battery Exclusion — Scope",
    coverageType: "General Liability",
    naicsCode: "722511",
    naicsDescription: "Full-Service Restaurants",
    direction: "tighter",
    mechanism: "exclusion",
    severity: "high",
    confidence: 0.91,
    abstained: false,
    markelSpan: {
      fullText:
        "This insurance does not apply to bodily injury or property damage arising out of assault and battery committed by or at the direction of the insured. Coverage is provided for bodily injury arising out of assault and battery committed by a third party on the insured's premises if the insured exercised reasonable care to prevent such acts.",
      highlightStart: 107,
      highlightEnd: 333,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 15,
        clauseId: "CG-00-01-Section-I-2g-AB",
        extractionConfidence: 0.94,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:30:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "This insurance does not apply to bodily injury or property damage arising out of or in any way related to assault and battery or any act or omission in connection with the prevention or suppression of such acts, regardless of the degree of culpability or negligence of the insured. This exclusion applies to claims alleging negligent hiring, supervision, or security.",
      highlightStart: 0,
      highlightEnd: 246,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 17,
        clauseId: "KGL-EX-AB",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:32:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale's assault and battery exclusion is absolute, covering all related claims including negligent hiring and security. Markel provides coverage for third-party assaults when the insured exercised reasonable care, which is critical for restaurant and bar operations.",
    reasoningSteps: [
      "Compared assault and battery exclusion language in both GL forms.",
      "Markel excludes only A&B committed by or directed by the insured; third-party acts may be covered.",
      "Kinsale's exclusion is absolute, extending to negligent hiring, supervision, and security claims.",
      "For restaurants and bars, third-party patron-on-patron violence is a major exposure.",
      "Kinsale's broader exclusion eliminates coverage for negligent security claims.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 15,
      clauseId: "CG-00-01-Section-I-2g-AB",
      extractionConfidence: 0.94,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:30:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 17,
      clauseId: "KGL-EX-AB",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:32:00Z",
    },
  },

  // ── cd-014: PL Hammer Clause ──
  {
    id: "cd-014",
    title: "Consent to Settle — Hammer Clause",
    coverageType: "Professional Liability",
    naicsCode: "621111",
    naicsDescription: "Offices of Physicians",
    direction: "tighter",
    mechanism: "condition",
    severity: "medium",
    confidence: 0.88,
    abstained: false,
    markelSpan: {
      fullText:
        "We will not settle any claim without the insured's consent. If the insured refuses to consent to a settlement recommended by us and elects to continue the defense of such claim, our liability shall not exceed the amount for which we could have settled plus defense costs incurred up to the date of such refusal.",
      highlightStart: 0,
      highlightEnd: 168,
      provenance: {
        documentId: "doc-markel-pl-01",
        documentName: "Markel PL Policy Form MPL-2024-05",
        pageNumber: 11,
        clauseId: "MPL-SETTLE-1",
        extractionConfidence: 0.92,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:40:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "If the insured refuses to consent to a settlement recommended by us within thirty (30) days, our liability shall be limited to sixty percent (60%) of the amount for which the claim could have been settled, and we shall have no obligation to pay any further defense costs. The insured shall be responsible for the remaining forty percent (40%) and all subsequent defense costs.",
      highlightStart: 85,
      highlightEnd: 370,
      provenance: {
        documentId: "doc-kinsale-pl-01",
        documentName: "Kinsale PL Policy Form KPL-2024-02",
        pageNumber: 12,
        clauseId: "KPL-SETTLE-1",
        extractionConfidence: 0.91,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:42:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale applies a punitive hammer clause reducing coverage to 60% of the settlement amount if the insured refuses a recommended settlement, while Markel caps at the full proposed settlement plus defense costs. Physicians who resist settlement to protect their reputation face greater financial exposure under Kinsale.",
    reasoningSteps: [
      "Compared consent-to-settle provisions in both professional liability forms.",
      "Markel uses a standard hammer clause capping at 100% of the proposed settlement.",
      "Kinsale uses a punitive 60/40 hammer clause with a 30-day consent window.",
      "Physicians frequently refuse settlements to avoid National Practitioner Data Bank reporting.",
      "The 40% co-pay penalty under Kinsale creates significant additional exposure.",
    ],
    markelProvenance: {
      documentId: "doc-markel-pl-01",
      documentName: "Markel PL Policy Form MPL-2024-05",
      pageNumber: 11,
      clauseId: "MPL-SETTLE-1",
      extractionConfidence: 0.92,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:40:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-pl-01",
      documentName: "Kinsale PL Policy Form KPL-2024-02",
      pageNumber: 12,
      clauseId: "KPL-SETTLE-1",
      extractionConfidence: 0.91,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:42:00Z",
    },
  },

  // ── cd-015: GL Additional Insured Scope ──
  {
    id: "cd-015",
    title: "Additional Insured — Ongoing Operations Scope",
    coverageType: "General Liability",
    naicsCode: "236220",
    naicsDescription: "Commercial and Institutional Building Construction",
    direction: "tighter",
    mechanism: "definition_narrowing",
    severity: "medium",
    confidence: 0.90,
    abstained: false,
    markelSpan: {
      fullText:
        "Any person or organization described in the schedule of additional insureds is an insured, but only with respect to liability for bodily injury, property damage, or personal and advertising injury caused in whole or in part by your acts or omissions or the acts or omissions of those acting on your behalf in the performance of your ongoing operations.",
      highlightStart: 0,
      highlightEnd: 215,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 20,
        clauseId: "CG-20-10",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:50:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "Any person or organization described in the schedule is an additional insured only with respect to liability for bodily injury or property damage caused by your negligent acts or omissions in the performance of your ongoing operations for that additional insured at the location designated. Personal and advertising injury coverage is not extended to additional insureds.",
      highlightStart: 140,
      highlightEnd: 361,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 22,
        clauseId: "KGL-AI-10",
        extractionConfidence: 0.92,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T12:52:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale narrows additional insured coverage to negligent acts only and excludes personal and advertising injury, while Markel uses broader 'caused in whole or in part' language that includes personal and advertising injury.",
    reasoningSteps: [
      "Compared additional insured endorsement language in both GL forms.",
      "Markel uses 'caused in whole or in part' which is broader than negligence-only.",
      "Kinsale limits to 'negligent acts or omissions' and restricts to designated locations.",
      "Kinsale also excludes personal and advertising injury for additional insureds.",
      "General contractors requiring broad additional insured protection would find Kinsale's form insufficient.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 20,
      clauseId: "CG-20-10",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:50:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 22,
      clauseId: "KGL-AI-10",
      extractionConfidence: 0.92,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T12:52:00Z",
    },
  },

  // ── cd-016: Cyber Regulatory Proceeding Coverage ──
  {
    id: "cd-016",
    title: "Cyber — Regulatory Proceeding Coverage",
    coverageType: "Cyber Liability",
    naicsCode: "511210",
    naicsDescription: "Software Publishers",
    direction: "broader",
    mechanism: "trigger",
    severity: "medium",
    confidence: 0.89,
    abstained: false,
    markelSpan: {
      fullText:
        "This policy does not cover fines, penalties, or costs arising from any regulatory or governmental investigation, inquiry, or proceeding related to a data breach or security event. Regulatory defense costs are excluded from coverage unless specifically endorsed.",
      highlightStart: 0,
      highlightEnd: 196,
      provenance: {
        documentId: "doc-markel-cy-01",
        documentName: "Markel Cyber Policy Form MCY-2024-09",
        pageNumber: 20,
        clauseId: "MCY-EX-REG",
        extractionConfidence: 0.91,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:00:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "We will pay regulatory defense costs incurred by the insured in connection with a regulatory proceeding brought by a governmental authority arising from a covered data breach. Coverage includes fines and penalties to the extent insurable by law in the applicable jurisdiction. This coverage is subject to a separate sublimit as shown in the Declarations.",
      highlightStart: 0,
      highlightEnd: 222,
      provenance: {
        documentId: "doc-kinsale-cy-01",
        documentName: "Kinsale Cyber Policy Form KCY-2024-01",
        pageNumber: 22,
        clauseId: "KCY-IG-REG",
        extractionConfidence: 0.90,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:02:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale provides regulatory proceeding coverage including defense costs and insurable fines, while Markel excludes regulatory proceedings entirely. Software publishers subject to GDPR, CCPA, and state breach notification laws benefit from Kinsale's broader approach.",
    reasoningSteps: [
      "Compared regulatory proceeding coverage in both cyber forms.",
      "Markel excludes all regulatory fines, penalties, and defense costs.",
      "Kinsale provides affirmative regulatory defense coverage with a sublimit.",
      "Kinsale also covers fines and penalties to the extent insurable by law.",
      "With increasing state privacy regulations, this is a significant competitive advantage for Kinsale.",
    ],
    markelProvenance: {
      documentId: "doc-markel-cy-01",
      documentName: "Markel Cyber Policy Form MCY-2024-09",
      pageNumber: 20,
      clauseId: "MCY-EX-REG",
      extractionConfidence: 0.91,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:00:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-cy-01",
      documentName: "Kinsale Cyber Policy Form KCY-2024-01",
      pageNumber: 22,
      clauseId: "KCY-IG-REG",
      extractionConfidence: 0.90,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:02:00Z",
    },
  },

  // ── cd-017: GL Damage to Your Work ──
  {
    id: "cd-017",
    title: "Damage to Your Work — Subcontractor Exception",
    coverageType: "General Liability",
    naicsCode: "236220",
    naicsDescription: "Commercial and Institutional Building Construction",
    direction: "tighter",
    mechanism: "exclusion",
    severity: "medium",
    confidence: 0.90,
    abstained: false,
    markelSpan: {
      fullText:
        "This exclusion does not apply if the damaged work or the work out of which the damage arises was performed on your behalf by a subcontractor. Coverage is provided for property damage to your completed work arising out of any part of the work performed for you by a subcontractor, subject to all other terms and conditions of this policy.",
      highlightStart: 0,
      highlightEnd: 194,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 16,
        clauseId: "CG-00-01-Section-I-2l",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:10:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "This insurance does not apply to property damage to your work arising out of it or any part of it and included in the products-completed operations hazard. No exception is provided for work performed by subcontractors. The insured's work includes work performed by subcontractors acting on behalf of or under contract with the insured.",
      highlightStart: 135,
      highlightEnd: 327,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 18,
        clauseId: "KGL-EX-2l",
        extractionConfidence: 0.92,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:12:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale removes the standard subcontractor exception to the 'damage to your work' exclusion. When a subcontractor's defective work damages the GC's completed project, Kinsale excludes coverage while Markel provides it.",
    reasoningSteps: [
      "Compared 'Damage to Your Work' exclusion language in both GL forms.",
      "Markel retains the standard ISO subcontractor exception to Exclusion l.",
      "Kinsale eliminates the subcontractor exception entirely.",
      "General contractors who subcontract most work rely heavily on this exception.",
      "Without it, completed operations coverage under Kinsale is significantly diminished.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 16,
      clauseId: "CG-00-01-Section-I-2l",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:10:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 18,
      clauseId: "KGL-EX-2l",
      extractionConfidence: 0.92,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:12:00Z",
    },
  },

  // ── cd-018: PL Bodily Injury Carve-back ──
  {
    id: "cd-018",
    title: "Professional Liability — Bodily Injury Coverage",
    coverageType: "Professional Liability",
    naicsCode: "621111",
    naicsDescription: "Offices of Physicians",
    direction: "broader",
    mechanism: "trigger",
    severity: "high",
    confidence: 0.92,
    abstained: false,
    markelSpan: {
      fullText:
        "This policy covers only financial loss resulting from a wrongful act in the performance of professional services. Bodily injury, including physical harm, sickness, disease, disability, or death, is specifically excluded from coverage under this policy regardless of the nature of the underlying professional service.",
      highlightStart: 98,
      highlightEnd: 298,
      provenance: {
        documentId: "doc-markel-pl-01",
        documentName: "Markel PL Policy Form MPL-2024-05",
        pageNumber: 9,
        clauseId: "MPL-EX-BI",
        extractionConfidence: 0.94,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:20:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "This policy covers loss, including bodily injury to the extent it arises from a wrongful act in the performance of professional services rendered by a licensed healthcare provider. Coverage for bodily injury is limited to damages resulting from a medical incident as defined herein. This coverage applies in excess of any applicable medical malpractice insurance.",
      highlightStart: 0,
      highlightEnd: 210,
      provenance: {
        documentId: "doc-kinsale-pl-01",
        documentName: "Kinsale PL Policy Form KPL-2024-02",
        pageNumber: 10,
        clauseId: "KPL-IG-BI",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:22:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale provides a bodily injury carve-back for healthcare providers' professional services, covering medical incidents in excess of malpractice insurance. Markel's PL form excludes all bodily injury regardless of the professional service, creating a gap for physician practices.",
    reasoningSteps: [
      "Compared bodily injury provisions in both professional liability forms.",
      "Markel excludes all bodily injury from professional liability coverage.",
      "Kinsale provides a carve-back for bodily injury arising from medical incidents by licensed providers.",
      "Kinsale's BI coverage applies excess of medical malpractice insurance.",
      "This is a significant broader coverage for physician offices under Kinsale.",
    ],
    markelProvenance: {
      documentId: "doc-markel-pl-01",
      documentName: "Markel PL Policy Form MPL-2024-05",
      pageNumber: 9,
      clauseId: "MPL-EX-BI",
      extractionConfidence: 0.94,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:20:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-pl-01",
      documentName: "Kinsale PL Policy Form KPL-2024-02",
      pageNumber: 10,
      clauseId: "KPL-IG-BI",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:22:00Z",
    },
  },

  // ── cd-019: GL Notice of Occurrence Condition ──
  {
    id: "cd-019",
    title: "Notice of Occurrence — Reporting Condition",
    coverageType: "General Liability",
    naicsCode: "238220",
    naicsDescription: "Plumbing, Heating, and Air-Conditioning Contractors",
    direction: "neutral",
    mechanism: "condition",
    severity: "low",
    confidence: 0.85,
    abstained: false,
    markelSpan: {
      fullText:
        "You must see to it that we are notified as soon as practicable of an occurrence or an offense which may result in a claim. Notice should include how, when and where the occurrence or offense took place and the names and addresses of any injured persons and witnesses. Failure to provide timely notice shall not void coverage unless such failure materially prejudices our rights.",
      highlightStart: 0,
      highlightEnd: 234,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 24,
        clauseId: "CG-00-01-Section-IV-2a",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:30:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "You must give us written notice of an occurrence or offense as soon as practicable. Notice should include how, when and where the occurrence or offense took place, the names and addresses of injured persons and witnesses, and the nature and location of any injury or damage. Late notice shall not void coverage unless we are materially prejudiced by such delay.",
      highlightStart: 0,
      highlightEnd: 230,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 26,
        clauseId: "KGL-COND-2a",
        extractionConfidence: 0.92,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:32:00Z",
      },
    },
    plainLanguageExplanation:
      "Both Markel and Kinsale require notice 'as soon as practicable' and apply a notice-prejudice standard. The provisions are functionally equivalent, with only minor wording differences that do not affect coverage.",
    reasoningSteps: [
      "Compared notice conditions in both GL forms.",
      "Both require notice 'as soon as practicable' rather than strict deadlines.",
      "Both apply a prejudice requirement for late notice.",
      "Minor wording differences do not create a substantive coverage gap.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 24,
      clauseId: "CG-00-01-Section-IV-2a",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:30:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 26,
      clauseId: "KGL-COND-2a",
      extractionConfidence: 0.92,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:32:00Z",
    },
  },

  // ── cd-020: GL Damage to Property You Own ──
  {
    id: "cd-020",
    title: "Damage to Property in Your Care, Custody, or Control",
    coverageType: "General Liability",
    naicsCode: "561720",
    naicsDescription: "Janitorial Services",
    direction: "broader",
    mechanism: "exclusion",
    severity: "medium",
    confidence: 0.87,
    abstained: false,
    markelSpan: {
      fullText:
        "This insurance does not apply to property damage to property owned, rented to, occupied by, used by, or in the care, custody, or control of the insured. This exclusion applies to property damage to premises rented to the insured or temporarily occupied by the insured with permission of the owner, except as provided under Coverage A for Damage to Premises Rented to You.",
      highlightStart: 0,
      highlightEnd: 224,
      provenance: {
        documentId: "doc-markel-gl-01",
        documentName: "Markel GL Policy Form MGL-2024-07",
        pageNumber: 13,
        clauseId: "CG-00-01-Section-I-2j",
        extractionConfidence: 0.94,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:40:00Z",
      },
    },
    kinsaleSpan: {
      fullText:
        "This insurance does not apply to property damage to property owned by the insured. However, coverage is provided for property damage to property in the care, custody, or control of the insured up to a sublimit of $50,000 per occurrence. This care, custody, or control coverage applies only to property of others entrusted to the insured for the purpose of performing covered operations.",
      highlightStart: 74,
      highlightEnd: 380,
      provenance: {
        documentId: "doc-kinsale-gl-01",
        documentName: "Kinsale GL Policy Form KGL-2024-03",
        pageNumber: 15,
        clauseId: "KGL-EX-2j",
        extractionConfidence: 0.93,
        modelVersion: "v2.4.1",
        extractionTimestamp: "2025-01-15T13:42:00Z",
      },
    },
    plainLanguageExplanation:
      "Kinsale provides a $50,000 sublimit for damage to property in the insured's care, custody, or control, while Markel applies a blanket CCC exclusion. For janitorial services working on client premises, Kinsale's built-in CCC coverage is a meaningful advantage.",
    reasoningSteps: [
      "Compared care, custody, or control exclusion language in both GL forms.",
      "Markel applies the standard ISO CCC exclusion without exception beyond fire damage to rented premises.",
      "Kinsale carves back $50,000 per occurrence for CCC property during covered operations.",
      "Janitorial services frequently damage client property (equipment, fixtures) making this carve-back valuable.",
    ],
    markelProvenance: {
      documentId: "doc-markel-gl-01",
      documentName: "Markel GL Policy Form MGL-2024-07",
      pageNumber: 13,
      clauseId: "CG-00-01-Section-I-2j",
      extractionConfidence: 0.94,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:40:00Z",
    },
    kinsaleProvenance: {
      documentId: "doc-kinsale-gl-01",
      documentName: "Kinsale GL Policy Form KGL-2024-03",
      pageNumber: 15,
      clauseId: "KGL-EX-2j",
      extractionConfidence: 0.93,
      modelVersion: "v2.4.1",
      extractionTimestamp: "2025-01-15T13:42:00Z",
    },
  },
];

export const CLAUSE_DELTA_MAP: Record<string, ClauseDelta> = Object.fromEntries(
  CLAUSE_DELTAS.map((cd) => [cd.id, cd])
);
