import type { DocumentAudit } from "@/lib/types";

export const DOCUMENTS: DocumentAudit[] = [
  // ── P&C Commercial Documents ──
  {
    id: "doc-pc-commercial-gl-01",
    documentName: "P&C Commercial GL Policy Form MGL-2024-07",
    insurer: "P&C Commercial",
    pageCount: 42,
    ocrConfidence: 0.96,
    chunkCount: 12,
    chunkBoundaries: [
      { chunkId: "mgl-chunk-01", startPage: 1, endPage: 3, sectionTitle: "Declarations" },
      { chunkId: "mgl-chunk-02", startPage: 4, endPage: 7, sectionTitle: "Insuring Agreement — Coverage A" },
      { chunkId: "mgl-chunk-03", startPage: 8, endPage: 10, sectionTitle: "Limits of Insurance" },
      { chunkId: "mgl-chunk-04", startPage: 11, endPage: 14, sectionTitle: "Exclusions — Coverage A" },
      { chunkId: "mgl-chunk-05", startPage: 15, endPage: 17, sectionTitle: "Exclusions — Coverage B" },
      { chunkId: "mgl-chunk-06", startPage: 18, endPage: 20, sectionTitle: "Additional Coverages" },
      { chunkId: "mgl-chunk-07", startPage: 21, endPage: 24, sectionTitle: "Who Is An Insured" },
      { chunkId: "mgl-chunk-08", startPage: 25, endPage: 28, sectionTitle: "Conditions" },
      { chunkId: "mgl-chunk-09", startPage: 29, endPage: 32, sectionTitle: "Definitions" },
      { chunkId: "mgl-chunk-10", startPage: 33, endPage: 36, sectionTitle: "Additional Insured Endorsements" },
      { chunkId: "mgl-chunk-11", startPage: 37, endPage: 40, sectionTitle: "Amendatory Endorsements" },
      { chunkId: "mgl-chunk-12", startPage: 41, endPage: 42, sectionTitle: "Schedule of Forms" },
    ],
    pageConfidences: [
      { page: 1, confidence: 0.98 },
      { page: 2, confidence: 0.97 },
      { page: 5, confidence: 0.96 },
      { page: 14, confidence: 0.95 },
      { page: 22, confidence: 0.94 },
      { page: 33, confidence: 0.88 },
      { page: 42, confidence: 0.97 },
    ],
    fieldExtractions: [
      { fieldName: "Policy Number", extractedValue: "MGL-2024-07-001234", confidence: 0.99, sourcePage: 1 },
      { fieldName: "Named Insured", extractedValue: "Sample Insured LLC", confidence: 0.98, sourcePage: 1 },
      { fieldName: "Policy Period", extractedValue: "01/01/2025 to 01/01/2026", confidence: 0.97, sourcePage: 1 },
      { fieldName: "General Aggregate Limit", extractedValue: "$2,000,000", confidence: 0.99, sourcePage: 3 },
      { fieldName: "Each Occurrence Limit", extractedValue: "$1,000,000", confidence: 0.99, sourcePage: 3 },
      { fieldName: "Products-Completed Operations Aggregate", extractedValue: "$2,000,000", confidence: 0.98, sourcePage: 3 },
      { fieldName: "Form Number", extractedValue: "CG 00 01 04 13 (modified)", confidence: 0.96, sourcePage: 42 },
    ],
    issues: [
      {
        type: "low_confidence",
        description: "Page 33 contains a scanned endorsement with faded text in the additional insured schedule. Some named entities may not have been extracted accurately.",
        page: 33,
        severity: "medium",
      },
    ],
  },
  {
    id: "doc-pc-commercial-pl-01",
    documentName: "P&C Commercial PL Policy Form MPL-2024-05",
    insurer: "P&C Commercial",
    pageCount: 28,
    ocrConfidence: 0.95,
    chunkCount: 8,
    chunkBoundaries: [
      { chunkId: "mpl-chunk-01", startPage: 1, endPage: 3, sectionTitle: "Declarations" },
      { chunkId: "mpl-chunk-02", startPage: 4, endPage: 7, sectionTitle: "Insuring Agreement" },
      { chunkId: "mpl-chunk-03", startPage: 8, endPage: 11, sectionTitle: "Defense & Settlement" },
      { chunkId: "mpl-chunk-04", startPage: 12, endPage: 15, sectionTitle: "Exclusions" },
      { chunkId: "mpl-chunk-05", startPage: 16, endPage: 19, sectionTitle: "Conditions" },
      { chunkId: "mpl-chunk-06", startPage: 20, endPage: 23, sectionTitle: "Definitions" },
      { chunkId: "mpl-chunk-07", startPage: 24, endPage: 26, sectionTitle: "Endorsements" },
      { chunkId: "mpl-chunk-08", startPage: 27, endPage: 28, sectionTitle: "Schedule" },
    ],
    pageConfidences: [
      { page: 1, confidence: 0.98 },
      { page: 5, confidence: 0.96 },
      { page: 9, confidence: 0.94 },
      { page: 15, confidence: 0.93 },
      { page: 20, confidence: 0.95 },
      { page: 28, confidence: 0.97 },
    ],
    fieldExtractions: [
      { fieldName: "Policy Number", extractedValue: "MPL-2024-05-005678", confidence: 0.99, sourcePage: 1 },
      { fieldName: "Retroactive Date", extractedValue: "None (Full Prior Acts)", confidence: 0.97, sourcePage: 2 },
      { fieldName: "Aggregate Limit", extractedValue: "$1,000,000", confidence: 0.98, sourcePage: 3 },
      { fieldName: "Each Claim Limit", extractedValue: "$1,000,000", confidence: 0.98, sourcePage: 3 },
      { fieldName: "Defense Costs", extractedValue: "In addition to limits", confidence: 0.96, sourcePage: 7 },
    ],
    issues: [
      {
        type: "scan_artifact",
        description: "Slight skew detected on pages 9-10 from scanner misalignment. Text extraction proceeded normally but bounding box coordinates may be offset by 2-3 pixels.",
        page: 9,
        severity: "low",
      },
    ],
  },
  {
    id: "doc-pc-commercial-cy-01",
    documentName: "P&C Commercial Cyber Policy Form MCY-2024-09",
    insurer: "P&C Commercial",
    pageCount: 35,
    ocrConfidence: 0.97,
    chunkCount: 10,
    chunkBoundaries: [
      { chunkId: "mcy-chunk-01", startPage: 1, endPage: 3, sectionTitle: "Declarations" },
      { chunkId: "mcy-chunk-02", startPage: 4, endPage: 7, sectionTitle: "Network Security Liability" },
      { chunkId: "mcy-chunk-03", startPage: 8, endPage: 11, sectionTitle: "Privacy Liability" },
      { chunkId: "mcy-chunk-04", startPage: 12, endPage: 15, sectionTitle: "Network Business Interruption" },
      { chunkId: "mcy-chunk-05", startPage: 16, endPage: 18, sectionTitle: "Cyber Extortion" },
      { chunkId: "mcy-chunk-06", startPage: 19, endPage: 22, sectionTitle: "Exclusions" },
      { chunkId: "mcy-chunk-07", startPage: 23, endPage: 26, sectionTitle: "Conditions" },
      { chunkId: "mcy-chunk-08", startPage: 27, endPage: 30, sectionTitle: "Definitions" },
      { chunkId: "mcy-chunk-09", startPage: 31, endPage: 33, sectionTitle: "Endorsements" },
      { chunkId: "mcy-chunk-10", startPage: 34, endPage: 35, sectionTitle: "Schedule" },
    ],
    pageConfidences: [
      { page: 1, confidence: 0.99 },
      { page: 12, confidence: 0.97 },
      { page: 16, confidence: 0.96 },
      { page: 20, confidence: 0.98 },
      { page: 27, confidence: 0.96 },
      { page: 35, confidence: 0.98 },
    ],
    fieldExtractions: [
      { fieldName: "Policy Number", extractedValue: "MCY-2024-09-009012", confidence: 0.99, sourcePage: 1 },
      { fieldName: "Aggregate Limit", extractedValue: "$2,000,000", confidence: 0.98, sourcePage: 2 },
      { fieldName: "Retention", extractedValue: "$25,000", confidence: 0.97, sourcePage: 2 },
      { fieldName: "Ransomware Coverage", extractedValue: "Full policy limits", confidence: 0.95, sourcePage: 16 },
      { fieldName: "Regulatory Coverage", extractedValue: "Excluded", confidence: 0.94, sourcePage: 20 },
    ],
    issues: [],
  },

  // ── Kinsale Documents ──
  {
    id: "doc-kinsale-gl-01",
    documentName: "Kinsale GL Policy Form KGL-2024-03",
    insurer: "Kinsale",
    pageCount: 48,
    ocrConfidence: 0.93,
    chunkCount: 14,
    chunkBoundaries: [
      { chunkId: "kgl-chunk-01", startPage: 1, endPage: 3, sectionTitle: "Declarations" },
      { chunkId: "kgl-chunk-02", startPage: 4, endPage: 7, sectionTitle: "Insuring Agreement — Coverage A" },
      { chunkId: "kgl-chunk-03", startPage: 8, endPage: 10, sectionTitle: "Limits of Insurance" },
      { chunkId: "kgl-chunk-04", startPage: 11, endPage: 15, sectionTitle: "Exclusions — Coverage A" },
      { chunkId: "kgl-chunk-05", startPage: 16, endPage: 19, sectionTitle: "Exclusions — Coverage B" },
      { chunkId: "kgl-chunk-06", startPage: 20, endPage: 22, sectionTitle: "Additional Coverages" },
      { chunkId: "kgl-chunk-07", startPage: 23, endPage: 26, sectionTitle: "Who Is An Insured" },
      { chunkId: "kgl-chunk-08", startPage: 27, endPage: 30, sectionTitle: "Conditions" },
      { chunkId: "kgl-chunk-09", startPage: 31, endPage: 34, sectionTitle: "Definitions" },
      { chunkId: "kgl-chunk-10", startPage: 35, endPage: 38, sectionTitle: "Additional Insured Endorsements" },
      { chunkId: "kgl-chunk-11", startPage: 39, endPage: 41, sectionTitle: "Amendatory Endorsements" },
      { chunkId: "kgl-chunk-12", startPage: 42, endPage: 44, sectionTitle: "State-Specific Endorsements" },
      { chunkId: "kgl-chunk-13", startPage: 45, endPage: 47, sectionTitle: "Pollution Endorsements" },
      { chunkId: "kgl-chunk-14", startPage: 48, endPage: 48, sectionTitle: "Schedule of Forms" },
    ],
    pageConfidences: [
      { page: 1, confidence: 0.97 },
      { page: 12, confidence: 0.91 },
      { page: 16, confidence: 0.89 },
      { page: 22, confidence: 0.92 },
      { page: 35, confidence: 0.88 },
      { page: 45, confidence: 0.90 },
      { page: 48, confidence: 0.95 },
    ],
    fieldExtractions: [
      { fieldName: "Policy Number", extractedValue: "KGL-2024-03-002345", confidence: 0.98, sourcePage: 1 },
      { fieldName: "Named Insured", extractedValue: "Sample Insured LLC", confidence: 0.97, sourcePage: 1 },
      { fieldName: "Policy Period", extractedValue: "01/01/2025 to 01/01/2026", confidence: 0.96, sourcePage: 1 },
      { fieldName: "General Aggregate Limit", extractedValue: "$2,000,000", confidence: 0.98, sourcePage: 3 },
      { fieldName: "Each Occurrence Limit", extractedValue: "$1,000,000", confidence: 0.99, sourcePage: 3 },
      { fieldName: "Products-Completed Operations Aggregate", extractedValue: "$1,000,000", confidence: 0.97, sourcePage: 3 },
    ],
    issues: [
      {
        type: "low_confidence",
        description: "Pages 16-17 contain dense exclusion language with small font size. OCR confidence dropped below 90% for these pages. Manual review recommended for exclusion boundary identification.",
        page: 16,
        severity: "high",
      },
      {
        type: "layout_error",
        description: "Page 35 additional insured endorsement uses a two-column layout that was parsed as single column. Clause boundaries may overlap between columns.",
        page: 35,
        severity: "medium",
      },
    ],
  },
  {
    id: "doc-kinsale-pl-01",
    documentName: "Kinsale PL Policy Form KPL-2024-02",
    insurer: "Kinsale",
    pageCount: 32,
    ocrConfidence: 0.94,
    chunkCount: 9,
    chunkBoundaries: [
      { chunkId: "kpl-chunk-01", startPage: 1, endPage: 3, sectionTitle: "Declarations" },
      { chunkId: "kpl-chunk-02", startPage: 4, endPage: 7, sectionTitle: "Insuring Agreement" },
      { chunkId: "kpl-chunk-03", startPage: 8, endPage: 10, sectionTitle: "Defense & Reimbursement" },
      { chunkId: "kpl-chunk-04", startPage: 11, endPage: 14, sectionTitle: "Settlement & Consent" },
      { chunkId: "kpl-chunk-05", startPage: 15, endPage: 18, sectionTitle: "Exclusions" },
      { chunkId: "kpl-chunk-06", startPage: 19, endPage: 22, sectionTitle: "Conditions" },
      { chunkId: "kpl-chunk-07", startPage: 23, endPage: 26, sectionTitle: "Definitions" },
      { chunkId: "kpl-chunk-08", startPage: 27, endPage: 30, sectionTitle: "Endorsements" },
      { chunkId: "kpl-chunk-09", startPage: 31, endPage: 32, sectionTitle: "Schedule" },
    ],
    pageConfidences: [
      { page: 1, confidence: 0.98 },
      { page: 6, confidence: 0.95 },
      { page: 8, confidence: 0.93 },
      { page: 12, confidence: 0.91 },
      { page: 23, confidence: 0.94 },
      { page: 32, confidence: 0.96 },
    ],
    fieldExtractions: [
      { fieldName: "Policy Number", extractedValue: "KPL-2024-02-006789", confidence: 0.99, sourcePage: 1 },
      { fieldName: "Retroactive Date", extractedValue: "01/01/2020", confidence: 0.96, sourcePage: 2 },
      { fieldName: "Aggregate Limit", extractedValue: "$1,000,000", confidence: 0.98, sourcePage: 3 },
      { fieldName: "Each Claim Limit", extractedValue: "$1,000,000", confidence: 0.98, sourcePage: 3 },
      { fieldName: "Defense Costs", extractedValue: "Eroding / within limits", confidence: 0.95, sourcePage: 8 },
      { fieldName: "Hammer Clause", extractedValue: "60/40 with 30-day window", confidence: 0.93, sourcePage: 12 },
    ],
    issues: [
      {
        type: "missing_field",
        description: "Extended reporting period (ERP) terms could not be located in the form. This field may be addressed in a separate endorsement not included in the document set.",
        severity: "medium",
      },
    ],
  },
  {
    id: "doc-kinsale-cy-01",
    documentName: "Kinsale Cyber Policy Form KCY-2024-01",
    insurer: "Kinsale",
    pageCount: 38,
    ocrConfidence: 0.95,
    chunkCount: 11,
    chunkBoundaries: [
      { chunkId: "kcy-chunk-01", startPage: 1, endPage: 3, sectionTitle: "Declarations" },
      { chunkId: "kcy-chunk-02", startPage: 4, endPage: 7, sectionTitle: "Network Security Liability" },
      { chunkId: "kcy-chunk-03", startPage: 8, endPage: 11, sectionTitle: "Privacy Liability" },
      { chunkId: "kcy-chunk-04", startPage: 12, endPage: 15, sectionTitle: "Network Business Interruption" },
      { chunkId: "kcy-chunk-05", startPage: 16, endPage: 19, sectionTitle: "Cyber Extortion" },
      { chunkId: "kcy-chunk-06", startPage: 20, endPage: 23, sectionTitle: "Regulatory Defense" },
      { chunkId: "kcy-chunk-07", startPage: 24, endPage: 27, sectionTitle: "Exclusions" },
      { chunkId: "kcy-chunk-08", startPage: 28, endPage: 31, sectionTitle: "Conditions" },
      { chunkId: "kcy-chunk-09", startPage: 32, endPage: 35, sectionTitle: "Definitions" },
      { chunkId: "kcy-chunk-10", startPage: 36, endPage: 37, sectionTitle: "Endorsements" },
      { chunkId: "kcy-chunk-11", startPage: 38, endPage: 38, sectionTitle: "Schedule" },
    ],
    pageConfidences: [
      { page: 1, confidence: 0.98 },
      { page: 14, confidence: 0.95 },
      { page: 18, confidence: 0.93 },
      { page: 22, confidence: 0.96 },
      { page: 32, confidence: 0.94 },
      { page: 38, confidence: 0.97 },
    ],
    fieldExtractions: [
      { fieldName: "Policy Number", extractedValue: "KCY-2024-01-003456", confidence: 0.99, sourcePage: 1 },
      { fieldName: "Aggregate Limit", extractedValue: "$2,000,000", confidence: 0.98, sourcePage: 2 },
      { fieldName: "Retention", extractedValue: "$50,000", confidence: 0.97, sourcePage: 2 },
      { fieldName: "Ransomware Sublimit", extractedValue: "$250,000", confidence: 0.96, sourcePage: 18 },
      { fieldName: "Regulatory Defense Sublimit", extractedValue: "$500,000", confidence: 0.95, sourcePage: 22 },
      { fieldName: "Cryptocurrency Exclusion", extractedValue: "Applies to extortion payments", confidence: 0.94, sourcePage: 18 },
    ],
    issues: [
      {
        type: "scan_artifact",
        description: "Watermark overlay on pages 20-23 partially obscures regulatory defense coverage text. OCR processed through watermark but confidence is reduced for these pages.",
        page: 20,
        severity: "low",
      },
    ],
  },
];

export const DOCUMENT_MAP: Record<string, DocumentAudit> = Object.fromEntries(
  DOCUMENTS.map((doc) => [doc.id, doc])
);
