import type { PricingComparison } from "@/lib/types";

export const PRICING_DATA: PricingComparison[] = [
  {
    id: "pr-001",
    insuredName: "Apex Plumbing & Heating LLC",
    naicsCode: "238220",
    naicsDescription: "Plumbing, Heating, and Air-Conditioning Contractors",
    coverageType: "General Liability",
    pcCommercialPremium: 18500,
    kinsalePremium: 15200,
    premiumDeltaPercent: -17.8,
    tightnessScore: 0.72,
    outcome: "kinsale_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-001",
        clauseTitle: "Pollution Exclusion — Hostile Fire Exception",
        estimatedPremiumImpact: 1200,
      },
      {
        clauseDeltaId: "cd-002",
        clauseTitle: "Products-Completed Operations Aggregate Limit",
        estimatedPremiumImpact: 850,
      },
    ],
  },
  {
    id: "pr-002",
    insuredName: "NovaTech Solutions Inc",
    naicsCode: "541511",
    naicsDescription: "Custom Computer Programming Services",
    coverageType: "Professional Liability",
    pcCommercialPremium: 42000,
    kinsalePremium: 35500,
    premiumDeltaPercent: -15.5,
    tightnessScore: 0.68,
    outcome: "kinsale_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-004",
        clauseTitle: "Claims-Made Retroactive Date Restriction",
        estimatedPremiumImpact: 3200,
      },
      {
        clauseDeltaId: "cd-010",
        clauseTitle: "Duty to Defend vs. Duty to Reimburse",
        estimatedPremiumImpact: 2800,
      },
    ],
  },
  {
    id: "pr-003",
    insuredName: "Harbor View Restaurant Group",
    naicsCode: "722511",
    naicsDescription: "Full-Service Restaurants",
    coverageType: "General Liability",
    pcCommercialPremium: 24800,
    kinsalePremium: 21300,
    premiumDeltaPercent: -14.1,
    tightnessScore: 0.65,
    outcome: "kinsale_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-013",
        clauseTitle: "Assault and Battery Exclusion — Scope",
        estimatedPremiumImpact: 1800,
      },
      {
        clauseDeltaId: "cd-008",
        clauseTitle: "Ordinance or Law — Increased Cost of Construction Sublimit",
        estimatedPremiumImpact: 650,
      },
    ],
  },
  {
    id: "pr-004",
    insuredName: "Summit Construction Partners",
    naicsCode: "236220",
    naicsDescription: "Commercial and Institutional Building Construction",
    coverageType: "General Liability",
    pcCommercialPremium: 85000,
    kinsalePremium: 68500,
    premiumDeltaPercent: -19.4,
    tightnessScore: 0.78,
    outcome: "kinsale_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-003",
        clauseTitle: "Contractual Liability — Insured Contract Definition",
        estimatedPremiumImpact: 5500,
      },
      {
        clauseDeltaId: "cd-017",
        clauseTitle: "Damage to Your Work — Subcontractor Exception",
        estimatedPremiumImpact: 4200,
      },
      {
        clauseDeltaId: "cd-015",
        clauseTitle: "Additional Insured — Ongoing Operations Scope",
        estimatedPremiumImpact: 3100,
      },
    ],
  },
  {
    id: "pr-005",
    insuredName: "Pacific Coast Medical Center",
    naicsCode: "621111",
    naicsDescription: "Offices of Physicians",
    coverageType: "Professional Liability",
    pcCommercialPremium: 65000,
    kinsalePremium: 72500,
    premiumDeltaPercent: 11.5,
    tightnessScore: 0.42,
    outcome: "pc_commercial_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-018",
        clauseTitle: "Professional Liability — Bodily Injury Coverage",
        estimatedPremiumImpact: -4500,
      },
    ],
  },
  {
    id: "pr-006",
    insuredName: "Meridian Financial Advisors",
    naicsCode: "523930",
    naicsDescription: "Investment Advice",
    coverageType: "Professional Liability",
    pcCommercialPremium: 55000,
    kinsalePremium: 42000,
    premiumDeltaPercent: -23.6,
    tightnessScore: 0.82,
    outcome: "kinsale_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-010",
        clauseTitle: "Duty to Defend vs. Duty to Reimburse",
        estimatedPremiumImpact: 6500,
      },
    ],
  },
  {
    id: "pr-007",
    insuredName: "CleanStar Janitorial Corp",
    naicsCode: "561720",
    naicsDescription: "Janitorial Services",
    coverageType: "General Liability",
    pcCommercialPremium: 12500,
    kinsalePremium: 9800,
    premiumDeltaPercent: -21.6,
    tightnessScore: 0.71,
    outcome: "kinsale_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-009",
        clauseTitle: "Independent Contractors — Vicarious Liability Exclusion",
        estimatedPremiumImpact: 1500,
      },
      {
        clauseDeltaId: "cd-020",
        clauseTitle: "Damage to Property in Your Care, Custody, or Control",
        estimatedPremiumImpact: -400,
      },
    ],
  },
  {
    id: "pr-008",
    insuredName: "DataForge Analytics",
    naicsCode: "511210",
    naicsDescription: "Software Publishers",
    coverageType: "Cyber Liability",
    pcCommercialPremium: 38000,
    kinsalePremium: 31500,
    premiumDeltaPercent: -17.1,
    tightnessScore: 0.74,
    outcome: "kinsale_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-005",
        clauseTitle: "Network Security Liability — Trigger Definition",
        estimatedPremiumImpact: 2800,
      },
      {
        clauseDeltaId: "cd-012",
        clauseTitle: "Cyber Extortion / Ransomware Sublimit",
        estimatedPremiumImpact: 2200,
      },
      {
        clauseDeltaId: "cd-016",
        clauseTitle: "Cyber — Regulatory Proceeding Coverage",
        estimatedPremiumImpact: -1500,
      },
    ],
  },
  {
    id: "pr-009",
    insuredName: "Wildfire BBQ Franchises",
    naicsCode: "722511",
    naicsDescription: "Full-Service Restaurants",
    coverageType: "General Liability",
    pcCommercialPremium: 32000,
    kinsalePremium: 28500,
    premiumDeltaPercent: -10.9,
    tightnessScore: 0.58,
    outcome: "competitive",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-013",
        clauseTitle: "Assault and Battery Exclusion — Scope",
        estimatedPremiumImpact: 2100,
      },
    ],
  },
  {
    id: "pr-010",
    insuredName: "Heritage Building Restoration",
    naicsCode: "236220",
    naicsDescription: "Commercial and Institutional Building Construction",
    coverageType: "Umbrella",
    pcCommercialPremium: 145000,
    kinsalePremium: 118000,
    premiumDeltaPercent: -18.6,
    tightnessScore: 0.76,
    outcome: "kinsale_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-007",
        clauseTitle: "Umbrella — Following Form vs. Stand-Alone Coverage",
        estimatedPremiumImpact: 12000,
      },
    ],
  },
  {
    id: "pr-011",
    insuredName: "BrightPath Medical Associates",
    naicsCode: "621111",
    naicsDescription: "Offices of Physicians",
    coverageType: "Professional Liability",
    pcCommercialPremium: 48000,
    kinsalePremium: 52500,
    premiumDeltaPercent: 9.4,
    tightnessScore: 0.38,
    outcome: "pc_commercial_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-014",
        clauseTitle: "Consent to Settle — Hammer Clause",
        estimatedPremiumImpact: 1800,
      },
      {
        clauseDeltaId: "cd-018",
        clauseTitle: "Professional Liability — Bodily Injury Coverage",
        estimatedPremiumImpact: -3200,
      },
    ],
  },
  {
    id: "pr-012",
    insuredName: "ProClean Facility Services",
    naicsCode: "561720",
    naicsDescription: "Janitorial Services",
    coverageType: "General Liability",
    pcCommercialPremium: 8500,
    kinsalePremium: 7200,
    premiumDeltaPercent: -15.3,
    tightnessScore: 0.64,
    outcome: "kinsale_wins",
    termGapOpportunities: [
      {
        clauseDeltaId: "cd-009",
        clauseTitle: "Independent Contractors — Vicarious Liability Exclusion",
        estimatedPremiumImpact: 900,
      },
    ],
  },
];

export const PRICING_MAP: Record<string, PricingComparison> =
  Object.fromEntries(PRICING_DATA.map((pr) => [pr.id, pr]));
