import type { ScorecardSegment } from "@/lib/types";

export const SCORECARDS: ScorecardSegment[] = [
  {
    id: "sc-001",
    naicsCode: "238220",
    naicsDescription: "Plumbing, Heating, and Air-Conditioning Contractors",
    coverageType: "General Liability",
    totalClauses: 5,
    tighterCount: 3,
    broaderCount: 1,
    neutralCount: 1,
    highSeverityCount: 2,
    topMechanisms: ["exclusion", "sublimit", "condition"],
    clauseDeltaIds: ["cd-001", "cd-002", "cd-009", "cd-019", "cd-020"],
  },
  {
    id: "sc-002",
    naicsCode: "541511",
    naicsDescription: "Custom Computer Programming Services",
    coverageType: "Professional Liability",
    totalClauses: 3,
    tighterCount: 2,
    broaderCount: 0,
    neutralCount: 1,
    highSeverityCount: 2,
    topMechanisms: ["condition", "exclusion"],
    clauseDeltaIds: ["cd-004", "cd-010", "cd-014"],
  },
  {
    id: "sc-003",
    naicsCode: "722511",
    naicsDescription: "Full-Service Restaurants",
    coverageType: "General Liability",
    totalClauses: 4,
    tighterCount: 2,
    broaderCount: 1,
    neutralCount: 1,
    highSeverityCount: 1,
    topMechanisms: ["exclusion", "sublimit"],
    clauseDeltaIds: ["cd-006", "cd-008", "cd-011", "cd-013"],
  },
  {
    id: "sc-004",
    naicsCode: "236220",
    naicsDescription: "Commercial and Institutional Building Construction",
    coverageType: "General Liability",
    totalClauses: 4,
    tighterCount: 3,
    broaderCount: 0,
    neutralCount: 1,
    highSeverityCount: 2,
    topMechanisms: ["definition_narrowing", "exclusion", "condition"],
    clauseDeltaIds: ["cd-003", "cd-007", "cd-015", "cd-017"],
  },
  {
    id: "sc-005",
    naicsCode: "621111",
    naicsDescription: "Offices of Physicians (except Mental Health Specialists)",
    coverageType: "Professional Liability",
    totalClauses: 2,
    tighterCount: 1,
    broaderCount: 1,
    neutralCount: 0,
    highSeverityCount: 1,
    topMechanisms: ["condition", "trigger"],
    clauseDeltaIds: ["cd-014", "cd-018"],
  },
  {
    id: "sc-006",
    naicsCode: "523930",
    naicsDescription: "Investment Advice",
    coverageType: "Professional Liability",
    totalClauses: 2,
    tighterCount: 2,
    broaderCount: 0,
    neutralCount: 0,
    highSeverityCount: 2,
    topMechanisms: ["condition"],
    clauseDeltaIds: ["cd-004", "cd-010"],
  },
  {
    id: "sc-007",
    naicsCode: "561720",
    naicsDescription: "Janitorial Services",
    coverageType: "General Liability",
    totalClauses: 3,
    tighterCount: 1,
    broaderCount: 1,
    neutralCount: 1,
    highSeverityCount: 1,
    topMechanisms: ["exclusion"],
    clauseDeltaIds: ["cd-009", "cd-019", "cd-020"],
  },
  {
    id: "sc-008",
    naicsCode: "511210",
    naicsDescription: "Software Publishers",
    coverageType: "Cyber Liability",
    totalClauses: 3,
    tighterCount: 2,
    broaderCount: 1,
    neutralCount: 0,
    highSeverityCount: 2,
    topMechanisms: ["trigger", "sublimit"],
    clauseDeltaIds: ["cd-005", "cd-012", "cd-016"],
  },
];

export const SCORECARD_MAP: Record<string, ScorecardSegment> =
  Object.fromEntries(SCORECARDS.map((sc) => [sc.id, sc]));
