import type { Submission } from "@/lib/types";

export const SUBMISSIONS: Submission[] = [
  {
    id: "sub-001",
    insuredName: "Apex Plumbing & Heating LLC",
    naicsCode: "238220",
    naicsDescription: "Plumbing, Heating, and Air-Conditioning Contractors",
    coverageType: "General Liability",
    state: "Virginia",
    broker: "Amwins Group",
    submittedDate: "2025-01-10T14:30:00Z",
    premiumEstimate: 18500,
    qualityScore: 0.91,
    triageBucket: "auto_quote",
    triageConfidence: 0.91,
    riskFlags: [
      {
        name: "Prior claims history",
        severity: "low",
        evidence: "One closed GL claim in 2022 for $12,000 — slip-and-fall at job site. No pattern of recurring losses.",
      },
    ],
    routingReason:
      "Strong submission quality (0.91), clean loss history, well-established HVAC contractor with 15 years of operations. NAICS 238220 is within standard appetite for GL.",
    hasWorkflow: true,
  },
  {
    id: "sub-002",
    insuredName: "NovaTech Solutions Inc",
    naicsCode: "541511",
    naicsDescription: "Custom Computer Programming Services",
    coverageType: "Professional Liability",
    state: "California",
    broker: "RT Specialty",
    submittedDate: "2025-01-11T09:15:00Z",
    premiumEstimate: 42000,
    qualityScore: 0.62,
    triageBucket: "needs_review",
    triageConfidence: 0.62,
    riskFlags: [
      {
        name: "High client concentration",
        severity: "high",
        evidence: "Top 3 clients represent 78% of revenue. Loss of a single client relationship could trigger multiple E&O claims.",
      },
      {
        name: "Offshore development team",
        severity: "medium",
        evidence: "40% of engineering staff located in offshore centers with limited quality assurance oversight documented in the submission.",
      },
      {
        name: "Missing financial statements",
        severity: "medium",
        evidence: "Only 2 years of financials provided; 3-year history required for PL submissions over $25K premium.",
      },
    ],
    routingReason:
      "Multiple risk flags identified including high client concentration and incomplete financial documentation. Requires underwriter review of offshore development practices and client dependency analysis.",
    hasWorkflow: true,
  },
  {
    id: "sub-003",
    insuredName: "Harbor View Restaurant Group",
    naicsCode: "722511",
    naicsDescription: "Full-Service Restaurants",
    coverageType: "General Liability",
    state: "Maryland",
    broker: "CRC Group",
    submittedDate: "2025-01-12T11:45:00Z",
    premiumEstimate: 24800,
    qualityScore: 0.87,
    triageBucket: "auto_quote",
    triageConfidence: 0.87,
    riskFlags: [
      {
        name: "Liquor liability exposure",
        severity: "medium",
        evidence: "Three locations serve alcohol with bar revenue exceeding 30% of total. Liquor liability endorsement required.",
      },
    ],
    routingReason:
      "Well-documented submission with strong quality score. Multi-location restaurant group with experienced management. Liquor liability endorsement flagged but within standard appetite parameters.",
    hasWorkflow: false,
  },
  {
    id: "sub-004",
    insuredName: "Redline Environmental Services",
    naicsCode: "562910",
    naicsDescription: "Remediation Services",
    coverageType: "General Liability",
    state: "New Jersey",
    broker: "Burns & Wilcox",
    submittedDate: "2025-01-13T08:00:00Z",
    premiumEstimate: 95000,
    qualityScore: 0.93,
    triageBucket: "auto_decline",
    triageConfidence: 0.93,
    riskFlags: [
      {
        name: "Prohibited NAICS code",
        severity: "high",
        evidence: "NAICS 562910 (Remediation Services) is on the prohibited class list due to catastrophic pollution exposure and long-tail environmental liability.",
      },
      {
        name: "Active environmental litigation",
        severity: "high",
        evidence: "Insured is currently party to two Superfund cost-recovery actions under CERCLA. Estimated aggregate exposure exceeds $2M.",
      },
      {
        name: "OSHA citations",
        severity: "high",
        evidence: "Three serious OSHA citations in the past 24 months for inadequate respiratory protection and hazardous waste handling.",
      },
    ],
    routingReason:
      "Remediation services (562910) is a prohibited class. Active Superfund litigation and recent OSHA citations further disqualify. Auto-decline with no referral pathway.",
    hasWorkflow: false,
  },
  {
    id: "sub-005",
    insuredName: "Summit Construction Partners",
    naicsCode: "236220",
    naicsDescription: "Commercial and Institutional Building Construction",
    coverageType: "General Liability",
    state: "Texas",
    broker: "Wholesale Trading Co-Op",
    submittedDate: "2025-01-14T10:30:00Z",
    premiumEstimate: 85000,
    qualityScore: 0.55,
    triageBucket: "needs_review",
    triageConfidence: 0.55,
    riskFlags: [
      {
        name: "Project size concentration",
        severity: "high",
        evidence: "Single project (mixed-use tower) represents 65% of annual revenue at $48M contract value. Significant aggregation risk.",
      },
      {
        name: "Subcontractor management",
        severity: "medium",
        evidence: "No formal subcontractor pre-qualification program documented. Relies on historical relationships for subcontractor selection.",
      },
      {
        name: "Incomplete safety program",
        severity: "medium",
        evidence: "Safety manual provided is dated 2019 and does not reflect current OSHA silica dust or fall protection standards.",
      },
    ],
    routingReason:
      "Large commercial construction risk with significant project concentration. Subcontractor management practices and outdated safety program require underwriter evaluation. Potential for additional information request.",
    hasWorkflow: false,
  },
  {
    id: "sub-006",
    insuredName: "Pacific Coast Medical Center",
    naicsCode: "621111",
    naicsDescription: "Offices of Physicians (except Mental Health Specialists)",
    coverageType: "Professional Liability",
    state: "Oregon",
    broker: "Worldwide Facilities",
    submittedDate: "2025-01-15T13:00:00Z",
    premiumEstimate: 65000,
    qualityScore: 0.48,
    triageBucket: "needs_review",
    triageConfidence: 0.48,
    riskFlags: [
      {
        name: "Specialty mix concern",
        severity: "high",
        evidence: "Practice includes two interventional pain management physicians performing epidural steroid injections — a high-severity E&S class.",
      },
      {
        name: "Prior malpractice claims",
        severity: "high",
        evidence: "Three open malpractice claims totaling $4.2M in alleged damages. One involves permanent nerve damage from a procedure.",
      },
      {
        name: "Locum tenens usage",
        severity: "medium",
        evidence: "Practice regularly uses locum tenens physicians (estimated 15% of patient encounters) without documented credentialing verification.",
      },
    ],
    routingReason:
      "High-risk physician practice with pain management specialty, multiple open claims, and credentialing gaps for locum tenens. Low confidence in triage due to complexity of medical PL exposure. Senior underwriter review required.",
    hasWorkflow: false,
  },
  {
    id: "sub-007",
    insuredName: "DataForge Analytics",
    naicsCode: "511210",
    naicsDescription: "Software Publishers",
    coverageType: "Cyber Liability",
    state: "Washington",
    broker: "Amwins Group",
    submittedDate: "2025-01-16T09:45:00Z",
    premiumEstimate: 38000,
    qualityScore: 0.89,
    triageBucket: "auto_quote",
    triageConfidence: 0.89,
    riskFlags: [
      {
        name: "PCI data processing",
        severity: "low",
        evidence: "Processes payment card data for 200 merchants. PCI DSS Level 2 compliant with most recent QSA audit dated October 2024.",
      },
    ],
    routingReason:
      "Strong cybersecurity posture with current PCI compliance, dedicated CISO, and documented incident response plan. Standard cyber appetite for software publishers. Auto-quote at indicated premium.",
    hasWorkflow: false,
  },
  {
    id: "sub-008",
    insuredName: "CleanStar Janitorial Corp",
    naicsCode: "561720",
    naicsDescription: "Janitorial Services",
    coverageType: "General Liability",
    state: "Florida",
    broker: "RT Specialty",
    submittedDate: "2025-01-17T15:20:00Z",
    premiumEstimate: 12500,
    qualityScore: 0.82,
    triageBucket: "auto_quote",
    triageConfidence: 0.82,
    riskFlags: [
      {
        name: "Worker classification",
        severity: "medium",
        evidence: "Uses a mix of W-2 employees and 1099 contractors. Florida recently tightened independent contractor classification rules effective 2025.",
      },
    ],
    routingReason:
      "Established janitorial company with 8 years of operations and clean loss history. Worker classification flagged as advisory item but does not affect GL coverage eligibility. Auto-quote within standard parameters.",
    hasWorkflow: false,
  },
  {
    id: "sub-009",
    insuredName: "Wildfire BBQ Franchises",
    naicsCode: "722511",
    naicsDescription: "Full-Service Restaurants",
    coverageType: "General Liability",
    state: "Tennessee",
    broker: "CRC Group",
    submittedDate: "2025-01-18T10:00:00Z",
    premiumEstimate: 32000,
    qualityScore: 0.67,
    triageBucket: "needs_review",
    triageConfidence: 0.67,
    riskFlags: [
      {
        name: "Rapid franchise expansion",
        severity: "medium",
        evidence: "Expanding from 4 to 9 locations in 2025. Franchise agreement quality and franchisee oversight capabilities not yet demonstrated.",
      },
      {
        name: "Live entertainment exposure",
        severity: "medium",
        evidence: "Two locations feature live music and dancing, creating crowd management and assault & battery exposure above typical restaurant risk.",
      },
      {
        name: "Food truck operations",
        severity: "low",
        evidence: "Two mobile food trucks operate at festivals and events, creating off-premises exposure not captured in standard restaurant rating.",
      },
    ],
    routingReason:
      "Franchise expansion pace and live entertainment exposure at select locations require underwriter assessment of management capabilities and endorsement requirements. Off-premises food truck operations may need separate rating.",
    hasWorkflow: false,
  },
  {
    id: "sub-010",
    insuredName: "ToxiChem Processing Inc",
    naicsCode: "325199",
    naicsDescription: "All Other Basic Organic Chemical Manufacturing",
    coverageType: "General Liability",
    state: "Louisiana",
    broker: "Burns & Wilcox",
    submittedDate: "2025-01-19T08:30:00Z",
    premiumEstimate: 150000,
    qualityScore: 0.95,
    triageBucket: "auto_decline",
    triageConfidence: 0.95,
    riskFlags: [
      {
        name: "Prohibited NAICS code",
        severity: "high",
        evidence: "NAICS 325199 (Organic Chemical Manufacturing) is on the prohibited class list due to catastrophic environmental and bodily injury exposure.",
      },
      {
        name: "Tier 1 TRI reporter",
        severity: "high",
        evidence: "Facility is a Tier 1 reporter under the Toxic Release Inventory, releasing over 25,000 lbs of listed chemicals annually.",
      },
      {
        name: "Recent EPA enforcement",
        severity: "high",
        evidence: "EPA consent decree from 2023 requiring $3.5M in corrective action for Clean Air Act violations at the primary facility.",
      },
      {
        name: "Catastrophic event history",
        severity: "high",
        evidence: "2021 chemical release resulted in shelter-in-place order for surrounding community. $8M in third-party claims currently in litigation.",
      },
    ],
    routingReason:
      "Chemical manufacturing is a prohibited class with catastrophic exposure profile. Active EPA enforcement, TRI reporting obligations, and recent community impact event. Immediate auto-decline.",
    hasWorkflow: true,
  },
  {
    id: "sub-011",
    insuredName: "Velocity Courier Services",
    naicsCode: "492110",
    naicsDescription: "Couriers and Express Delivery Services",
    coverageType: "General Liability",
    state: "Georgia",
    broker: "Worldwide Facilities",
    submittedDate: "2025-01-20T11:15:00Z",
    premiumEstimate: 22000,
    qualityScore: 0.51,
    triageBucket: "needs_review",
    triageConfidence: 0.51,
    riskFlags: [
      {
        name: "Auto exposure not addressed",
        severity: "high",
        evidence: "Courier service with 35 vehicles but submission does not include commercial auto information. GL alone is insufficient for this class.",
      },
      {
        name: "Employee turnover",
        severity: "medium",
        evidence: "Annual driver turnover rate of 45%. High turnover correlates with increased accident frequency and training gaps.",
      },
      {
        name: "Incomplete application",
        severity: "medium",
        evidence: "Several required application fields left blank including prior carrier information, 5-year loss runs, and fleet age details.",
      },
    ],
    routingReason:
      "Incomplete submission missing critical auto exposure information. High driver turnover and missing loss history require additional information before underwriting can proceed. Low triage confidence reflects data gaps.",
    hasWorkflow: false,
  },
  {
    id: "sub-012",
    insuredName: "DeepMine Excavation LLC",
    naicsCode: "212312",
    naicsDescription: "Crushed and Broken Limestone Mining and Quarrying",
    coverageType: "General Liability",
    state: "West Virginia",
    broker: "Burns & Wilcox",
    submittedDate: "2025-01-21T07:45:00Z",
    premiumEstimate: 110000,
    qualityScore: 0.88,
    triageBucket: "auto_decline",
    triageConfidence: 0.88,
    riskFlags: [
      {
        name: "Prohibited NAICS code",
        severity: "high",
        evidence: "NAICS 212312 (Mining/Quarrying) is on the prohibited class list due to silicosis exposure, blast damage liability, and environmental contamination risk.",
      },
      {
        name: "MSHA violation history",
        severity: "high",
        evidence: "14 MSHA citations in the past 36 months including 3 significant-and-substantial (S&S) violations for ground control and ventilation.",
      },
      {
        name: "Silicosis exposure",
        severity: "high",
        evidence: "Limestone quarrying operations generate respirable crystalline silica dust. Long-tail occupational disease exposure with latency periods exceeding 20 years.",
      },
    ],
    routingReason:
      "Mining and quarrying is a prohibited class with uninsurable long-tail silicosis exposure. MSHA violation history confirms elevated operational risk. Auto-decline per class guidelines.",
    hasWorkflow: false,
  },
];

export const SUBMISSION_MAP: Record<string, Submission> = Object.fromEntries(
  SUBMISSIONS.map((sub) => [sub.id, sub])
);
