"use client";

import { use, useState, useCallback } from "react";
import {
  PORTAL_PROPOSAL_MAP,
  PORTAL_SUBMISSION_MAP,
  PORTAL_PROPOSAL_RATES,
  PORTAL_PROPOSAL_NOTES,
  PORTAL_PROPOSAL_FORMS,
  PORTAL_FORMS,
  PORTAL_LOSS_RUNS,
  PORTAL_LOSS_DETAILS,
} from "@/lib/mock-data";
import { EmptyState } from "@/components/shared/empty-state";
import { PortalStatusBadge } from "@/components/submissions/portal-status-badge";
import { TabForms } from "@/components/submissions/tab-forms";
import { TabLocationSchedule } from "@/components/submissions/tab-location-schedule";
import { TabSubjectivities } from "@/components/submissions/tab-subjectivities";
import { TabPricingWorksheet } from "@/components/submissions/tab-pricing-worksheet";
import { ProposalSummaryNotes } from "@/components/submissions/proposal-summary-notes";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Link from "next/link";
import { ArrowLeft, Check, X, Copy, Download, Bot, Lock, Send } from "lucide-react";
import { generateProposalPdf } from "@/lib/proposal-pdf-export";

function formatCurrency(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
}

const PROPOSAL_STATUS_COLORS: Record<string, string> = {
  draft: "bg-zinc-100 text-zinc-700 border-zinc-200",
  pending_approval: "bg-amber-50 text-amber-700 border-amber-200",
  approved: "bg-green-50 text-green-700 border-green-200",
  declined: "bg-red-50 text-red-700 border-red-200",
};

export default function ProposalDetailPage({
  params,
}: {
  params: Promise<{ id: string; proposalId: string }>;
}) {
  const { id, proposalId } = use(params);
  const submission = PORTAL_SUBMISSION_MAP[id];
  const proposal = PORTAL_PROPOSAL_MAP[proposalId];

  if (!submission || !proposal) {
    return (
      <EmptyState
        title="Proposal Not Found"
        description={`No proposal found with ID "${proposalId}".`}
      />
    );
  }

  const rates = PORTAL_PROPOSAL_RATES[proposalId] || [];
  const notes = PORTAL_PROPOSAL_NOTES[proposalId] || [];
  const forms = PORTAL_PROPOSAL_FORMS[proposalId] || [];
  const lossRuns = PORTAL_LOSS_RUNS[id] || [];
  const lossDetails = PORTAL_LOSS_DETAILS[id] || [];
  const isGL = submission.lineOfBusiness === "General Liability";
  const readOnly = !!proposal.aiGenerated;

  // Proposal location schedule — starts from submission locations, can diverge
  const submissionLocations = submission.insuredLocations || [];
  const [proposalLocations, setProposalLocations] = useState(submissionLocations);

  // Add: creates on both submission (shared) and proposal schedule
  const handleAddLocation = useCallback((loc: typeof submissionLocations[number]) => {
    // In real app, would POST to submission API too
    setProposalLocations((prev) => [...prev, loc]);
  }, []);

  // Remove: only removes from proposal schedule (not submission)
  const handleRemoveLocation = useCallback((address: string) => {
    setProposalLocations((prev) => prev.filter((l) => l.address !== address));
  }, []);

  return (
    <div className="space-y-6">
      {/* Back Link */}
      <Link href={`/submissions/${id}`}>
        <Button variant="ghost" size="sm">
          <ArrowLeft className="h-4 w-4 mr-1" />
          Back to {submission.insuredName}
        </Button>
      </Link>

      {/* AI Immutable Banner */}
      {readOnly && (
        <div className="flex items-center gap-3 rounded-lg border border-violet-200 bg-violet-50 p-4">
          <div className="flex items-center gap-2 text-violet-700">
            <Bot className="h-5 w-5" />
            <Lock className="h-4 w-4" />
          </div>
          <div className="text-sm">
            <p className="font-medium text-violet-900">AI-Generated Proposal — Read Only</p>
            <p className="text-violet-700">This proposal was generated by AI and cannot be edited. Copy it to create an editable version.</p>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="space-y-2">
          <div className="flex items-center gap-3 flex-wrap">
            <h1 className="text-2xl font-bold">{proposal.label}</h1>
            <Badge variant="outline" className="text-xs">v{proposal.version}</Badge>
            <Badge
              variant="outline"
              className={PROPOSAL_STATUS_COLORS[proposal.status] || ""}
            >
              {proposal.status.replace("_", " ")}
            </Badge>
            {readOnly && (
              <Badge variant="secondary" className="text-xs bg-violet-50 text-violet-700 border-violet-200 gap-1">
                <Bot className="h-3 w-3" />
                AI Generated
              </Badge>
            )}
          </div>
          <div className="flex flex-wrap gap-2 text-sm text-muted-foreground">
            <span>For: <strong>{submission.insuredName}</strong></span>
            <span>•</span>
            <span>{submission.referenceNumber}</span>
            <span>•</span>
            <PortalStatusBadge status={submission.status} size="sm" />
          </div>
          <p className="text-lg font-semibold">Total Premium: {formatCurrency(proposal.totalPremium)}</p>
        </div>

        <div className="flex gap-2">
          <Button variant="outline" size="sm">
            <Copy className="h-4 w-4 mr-1" />
            {readOnly ? "Copy to Edit" : "New Version"}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              const pdfForms = PORTAL_FORMS[id] || forms;
              generateProposalPdf(submission, proposal, rates, pdfForms);
            }}
          >
            <Download className="h-4 w-4 mr-1" />
            Export Proposal PDF
          </Button>
          {proposal.status === "approved" && (
            <Button size="sm" variant="default">
              <Send className="h-4 w-4 mr-1" />
              Send Proposal to Broker
            </Button>
          )}
          {!readOnly && proposal.status === "pending_approval" && (
            <>
              <Button size="sm" variant="default">
                <Check className="h-4 w-4 mr-1" />
                Approve
              </Button>
              <Button size="sm" variant="destructive">
                <X className="h-4 w-4 mr-1" />
                Decline
              </Button>
            </>
          )}
        </div>
      </div>

      {/* Summary + Notes */}
      <ProposalSummaryNotes initialNotes={notes} />

      {/* Tabs */}
      <Tabs defaultValue="pricing" className="w-full">
        <TabsList className="w-full justify-start">
          <TabsTrigger value="pricing">Rate &amp; Pricing Worksheet</TabsTrigger>
          <TabsTrigger value="forms">Forms ({forms.length})</TabsTrigger>
          <TabsTrigger value="locations">Proposal Location Schedule ({proposalLocations.length})</TabsTrigger>
          <TabsTrigger value="subjectivities">Subjectivities</TabsTrigger>
        </TabsList>

        <TabsContent value="pricing" className="mt-6">
          <TabPricingWorksheet proposal={proposal} rates={rates} forms={forms} lossRuns={lossRuns} lossDetails={lossDetails} proposalLocations={proposalLocations} readOnly={readOnly} />
        </TabsContent>

        <TabsContent value="forms" className="mt-6">
          <TabForms forms={forms} readOnly={readOnly} />
        </TabsContent>

        <TabsContent value="locations" className="mt-6">
          <TabLocationSchedule
            locations={proposalLocations}
            onAddLocation={handleAddLocation}
            onRemoveLocation={handleRemoveLocation}
          />
        </TabsContent>

        <TabsContent value="subjectivities" className="mt-6">
          <p className="text-sm text-muted-foreground mb-4">Subjectivities are shared among all proposals and the submission.</p>
          <TabSubjectivities readOnly={readOnly} />
        </TabsContent>
      </Tabs>
    </div>
  );
}
